herokub2_club/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("members.urls")),
]

members/urls.py
# In members/urls.py
from django.conf.urls import url

from . import views

app_name = "members"
urlpatterns=[
  url(r'^$', views.AllMembersView.as_view(), name="all_members"),
  url(r'^new_member/$', views.NewMemberView.as_view(), name="new_member"),
]

members/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    name = models.CharField(max_length=64)
    short_bio = models.TextField(max_length=512) # Short Biography
    picture = models.ImageField(upload_to="members", default="members/py.png")

    def __str__(self):
        return self.name

members/views.py
from django.shortcuts import render

# In members/views.py
from django.core.urlresolvers import reverse_lazy # similar to reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView

from .models import Member

class AllMembersView(ListView):
    model = Member
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(AllMembersView, self).get_context_data(**kwargs)
        context['title'] = 'All Members'
        return context

class NewMemberView(CreateView):
    template_name = "new_member.html"
    model = Member # Model of the object that will be created
    fields = ['name', 'short_bio', 'picture']
    success_url = reverse_lazy("members:all_members") # Redirect Url after creating the object

    def get_context_data(self, **kwargs):
        context = super(NewMemberView, self).get_context_data(**kwargs)
        context['title'] = "New Member"
        return context

members/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="shortcut icon" href="{% static 'img/py.png' %}">

    <title>{{title}} | HerokuB2 Club</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style media="screen">
      body {
        padding-top: 5rem;
      }
      .starter-template {
        padding: 3rem 1.5rem;
        text-align: center;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <a class="navbar-brand" href="{% url 'members:all_members' %}">HerokuB2 Club</a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'members:all_members' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'members:new_member' %}">New Member</a>
        </li>
      </ul>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div><!-- /.container -->

    <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

members/templates/index.html
{% extends 'base.html' %}


{%block content%}
<h1>HerokuB2 Members</h1>
<ul>
{% for member in object_list %}
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4 col-xs-12">
        <img src="{{member.picture.url}}" alt="Member's Picture" width="173"/>
      </div>
      <div class="col-sm-8 col-xs-12">
        <h2>{{member.name}}</h2>
        <p>
          {{member.short_bio}}
        </p>
      </div>
    </div>
  </li>
{% endfor %}
</ul>
{% endblock %}

members/templates/new_member.html
{% extends 'base.html' %}

{% block content %}
<div id="formWarnings">
  <ul class="list-group">

  </ul>
</div>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-success" >Submit</button>
</form>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
function bootstrapify(){
  $('form p').addClass('form-group');

  $('form input, form textarea, form select').addClass('form-control');

  $('.errorlist li').text(function(index, text){
    return text.replace('This field', $(this).closest('.errorlist').next('.form-group').find('.form-control').attr('name').toUpperCase());
  });

  warnings = $('.errorlist');
  $('.errorlist').remove();
  warnings.find('li').addClass('alert alert-danger list-group-item')
  warnings.find('li').each(function(){
    $('#formWarnings').append($(this));
  });

}

$(function(){
	bootstrapify();
});
</script>
{% endblock %}